// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/v1/snapshot.proto

// The snapshot wire format: the contract between the Python control plane that
// compiles configuration and the Go data plane that serves requests from it.
//
// This is deliberately NOT the same as the Go domain types in internal/core.
// Domain types are shaped for the request path and are refactored freely; wire
// types are append-only and backward-compatible forever. Collapsing the two
// would make every internal rename a wire-compatibility question.
//
// Compatibility rules for anyone editing this file:
//   - Never reuse or renumber a field tag. Use `reserved` when removing one.
//   - New fields are always optional in effect: an older worker must be able to
//     read a newer layer and ignore what it does not understand, because during
//     a rollout both versions are live at once.
//   - Enums always keep an UNSPECIFIED zero value, so a value added later
//     arrives as "unspecified" rather than being silently read as the first
//     real variant.

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrustTier int32

const (
	TrustTier_TRUST_TIER_UNSPECIFIED   TrustTier = 0
	TrustTier_TRUST_TIER_EXTERNAL      TrustTier = 1
	TrustTier_TRUST_TIER_PRIVATE_CLOUD TrustTier = 2
	TrustTier_TRUST_TIER_INTERNAL      TrustTier = 3
)

// Enum value maps for TrustTier.
var (
	TrustTier_name = map[int32]string{
		0: "TRUST_TIER_UNSPECIFIED",
		1: "TRUST_TIER_EXTERNAL",
		2: "TRUST_TIER_PRIVATE_CLOUD",
		3: "TRUST_TIER_INTERNAL",
	}
	TrustTier_value = map[string]int32{
		"TRUST_TIER_UNSPECIFIED":   0,
		"TRUST_TIER_EXTERNAL":      1,
		"TRUST_TIER_PRIVATE_CLOUD": 2,
		"TRUST_TIER_INTERNAL":      3,
	}
)

func (x TrustTier) Enum() *TrustTier {
	p := new(TrustTier)
	*p = x
	return p
}

func (x TrustTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrustTier) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_snapshot_proto_enumTypes[0].Descriptor()
}

func (TrustTier) Type() protoreflect.EnumType {
	return &file_gateway_v1_snapshot_proto_enumTypes[0]
}

func (x TrustTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrustTier.Descriptor instead.
func (TrustTier) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

type BudgetScope int32

const (
	BudgetScope_BUDGET_SCOPE_UNSPECIFIED BudgetScope = 0
	BudgetScope_BUDGET_SCOPE_KEY         BudgetScope = 1
	BudgetScope_BUDGET_SCOPE_APP         BudgetScope = 2
	BudgetScope_BUDGET_SCOPE_USER        BudgetScope = 3
	BudgetScope_BUDGET_SCOPE_TEAM        BudgetScope = 4
	BudgetScope_BUDGET_SCOPE_ORG         BudgetScope = 5
	BudgetScope_BUDGET_SCOPE_MODEL       BudgetScope = 6
	BudgetScope_BUDGET_SCOPE_TRAINING    BudgetScope = 7
)

// Enum value maps for BudgetScope.
var (
	BudgetScope_name = map[int32]string{
		0: "BUDGET_SCOPE_UNSPECIFIED",
		1: "BUDGET_SCOPE_KEY",
		2: "BUDGET_SCOPE_APP",
		3: "BUDGET_SCOPE_USER",
		4: "BUDGET_SCOPE_TEAM",
		5: "BUDGET_SCOPE_ORG",
		6: "BUDGET_SCOPE_MODEL",
		7: "BUDGET_SCOPE_TRAINING",
	}
	BudgetScope_value = map[string]int32{
		"BUDGET_SCOPE_UNSPECIFIED": 0,
		"BUDGET_SCOPE_KEY":         1,
		"BUDGET_SCOPE_APP":         2,
		"BUDGET_SCOPE_USER":        3,
		"BUDGET_SCOPE_TEAM":        4,
		"BUDGET_SCOPE_ORG":         5,
		"BUDGET_SCOPE_MODEL":       6,
		"BUDGET_SCOPE_TRAINING":    7,
	}
)

func (x BudgetScope) Enum() *BudgetScope {
	p := new(BudgetScope)
	*p = x
	return p
}

func (x BudgetScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BudgetScope) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_snapshot_proto_enumTypes[1].Descriptor()
}

func (BudgetScope) Type() protoreflect.EnumType {
	return &file_gateway_v1_snapshot_proto_enumTypes[1]
}

func (x BudgetScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BudgetScope.Descriptor instead.
func (BudgetScope) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

type Port int32

const (
	Port_PORT_UNSPECIFIED Port = 0
	Port_PORT_PROVIDER    Port = 1
	Port_PORT_GUARDRAIL   Port = 2
	Port_PORT_STORE       Port = 3
	Port_PORT_TELEMETRY   Port = 4
)

// Enum value maps for Port.
var (
	Port_name = map[int32]string{
		0: "PORT_UNSPECIFIED",
		1: "PORT_PROVIDER",
		2: "PORT_GUARDRAIL",
		3: "PORT_STORE",
		4: "PORT_TELEMETRY",
	}
	Port_value = map[string]int32{
		"PORT_UNSPECIFIED": 0,
		"PORT_PROVIDER":    1,
		"PORT_GUARDRAIL":   2,
		"PORT_STORE":       3,
		"PORT_TELEMETRY":   4,
	}
)

func (x Port) Enum() *Port {
	p := new(Port)
	*p = x
	return p
}

func (x Port) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Port) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_snapshot_proto_enumTypes[2].Descriptor()
}

func (Port) Type() protoreflect.EnumType {
	return &file_gateway_v1_snapshot_proto_enumTypes[2]
}

func (x Port) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Port.Descriptor instead.
func (Port) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

// LayerVersion identifies one build of one layer. Number orders versions;
// digest content-addresses the bytes so a worker can skip a re-fetch and two
// workers claiming the same version can be proven to hold the same layer.
type LayerVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerVersion) Reset() {
	*x = LayerVersion{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerVersion) ProtoMessage() {}

func (x *LayerVersion) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerVersion.ProtoReflect.Descriptor instead.
func (*LayerVersion) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *LayerVersion) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *LayerVersion) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// RoutingKey is (base model, adapter). Adapter is empty for a plain base model.
// Multi-LoRA serving means one base deployment serves many adapters, so this is
// the routing table's key from the first release rather than a bare model name.
type RoutingKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseModel     string                 `protobuf:"bytes,1,opt,name=base_model,json=baseModel,proto3" json:"base_model,omitempty"`
	AdapterId     string                 `protobuf:"bytes,2,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingKey) Reset() {
	*x = RoutingKey{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingKey) ProtoMessage() {}

func (x *RoutingKey) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingKey.ProtoReflect.Descriptor instead.
func (*RoutingKey) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *RoutingKey) GetBaseModel() string {
	if x != nil {
		return x.BaseModel
	}
	return ""
}

func (x *RoutingKey) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

type Cost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Millionths of a US dollar per thousand tokens. Integer, never floating
	// point: per-token prices are small enough that float rounding reaches the
	// invoice.
	InputPer_1KMicroUsd  int64 `protobuf:"varint,1,opt,name=input_per_1k_micro_usd,json=inputPer1kMicroUsd,proto3" json:"input_per_1k_micro_usd,omitempty"`
	OutputPer_1KMicroUsd int64 `protobuf:"varint,2,opt,name=output_per_1k_micro_usd,json=outputPer1kMicroUsd,proto3" json:"output_per_1k_micro_usd,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *Cost) GetInputPer_1KMicroUsd() int64 {
	if x != nil {
		return x.InputPer_1KMicroUsd
	}
	return 0
}

func (x *Cost) GetOutputPer_1KMicroUsd() int64 {
	if x != nil {
		return x.OutputPer_1KMicroUsd
	}
	return 0
}

type Deployment struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key       *RoutingKey            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Provider  string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Endpoint  string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region    string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	TrustTier TrustTier              `protobuf:"varint,6,opt,name=trust_tier,json=trustTier,proto3,enum=gateway.v1.TrustTier" json:"trust_tier,omitempty"`
	// A reference to a secret, never the secret. Provider credentials must not
	// enter a snapshot: snapshots are replicated to every worker, cached and
	// versioned. Workers resolve the reference separately and cache with a TTL.
	CredentialRef string `protobuf:"bytes,7,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	// Share of traffic, 0-100. Zero means registered but not serving — the state
	// a fine-tuned adapter sits in while it takes shadow traffic.
	Weight        uint32   `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Cost          *Cost    `protobuf:"bytes,9,opt,name=cost,proto3" json:"cost,omitempty"`
	Capabilities  []string `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetKey() *RoutingKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Deployment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Deployment) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Deployment) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Deployment) GetTrustTier() TrustTier {
	if x != nil {
		return x.TrustTier
	}
	return TrustTier_TRUST_TIER_UNSPECIFIED
}

func (x *Deployment) GetCredentialRef() string {
	if x != nil {
		return x.CredentialRef
	}
	return ""
}

func (x *Deployment) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Deployment) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Deployment) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ModelAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Targets       []*RoutingKey          `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelAlias) Reset() {
	*x = ModelAlias{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelAlias) ProtoMessage() {}

func (x *ModelAlias) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelAlias.ProtoReflect.Descriptor instead.
func (*ModelAlias) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *ModelAlias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelAlias) GetTargets() []*RoutingKey {
	if x != nil {
		return x.Targets
	}
	return nil
}

type PluginBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          Port                   `protobuf:"varint,1,opt,name=port,proto3,enum=gateway.v1.Port" json:"port,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ConfigRef     string                 `protobuf:"bytes,4,opt,name=config_ref,json=configRef,proto3" json:"config_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginBinding) Reset() {
	*x = PluginBinding{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginBinding) ProtoMessage() {}

func (x *PluginBinding) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginBinding.ProtoReflect.Descriptor instead.
func (*PluginBinding) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *PluginBinding) GetPort() Port {
	if x != nil {
		return x.Port
	}
	return Port_PORT_UNSPECIFIED
}

func (x *PluginBinding) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *PluginBinding) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginBinding) GetConfigRef() string {
	if x != nil {
		return x.ConfigRef
	}
	return ""
}

type BudgetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Scope         BudgetScope            `protobuf:"varint,2,opt,name=scope,proto3,enum=gateway.v1.BudgetScope" json:"scope,omitempty"`
	LimitMicroUsd int64                  `protobuf:"varint,3,opt,name=limit_micro_usd,json=limitMicroUsd,proto3" json:"limit_micro_usd,omitempty"`
	SpentMicroUsd int64                  `protobuf:"varint,4,opt,name=spent_micro_usd,json=spentMicroUsd,proto3" json:"spent_micro_usd,omitempty"`
	Hard          bool                   `protobuf:"varint,5,opt,name=hard,proto3" json:"hard,omitempty"`
	// Basis points of the limit held back so requests already streaming when the
	// budget tips can finish without overshooting. 500 = 5%.
	HeadroomBasisPoints uint32 `protobuf:"varint,6,opt,name=headroom_basis_points,json=headroomBasisPoints,proto3" json:"headroom_basis_points,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BudgetState) Reset() {
	*x = BudgetState{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetState) ProtoMessage() {}

func (x *BudgetState) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetState.ProtoReflect.Descriptor instead.
func (*BudgetState) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *BudgetState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetState) GetScope() BudgetScope {
	if x != nil {
		return x.Scope
	}
	return BudgetScope_BUDGET_SCOPE_UNSPECIFIED
}

func (x *BudgetState) GetLimitMicroUsd() int64 {
	if x != nil {
		return x.LimitMicroUsd
	}
	return 0
}

func (x *BudgetState) GetSpentMicroUsd() int64 {
	if x != nil {
		return x.SpentMicroUsd
	}
	return 0
}

func (x *BudgetState) GetHard() bool {
	if x != nil {
		return x.Hard
	}
	return false
}

func (x *BudgetState) GetHeadroomBasisPoints() uint32 {
	if x != nil {
		return x.HeadroomBasisPoints
	}
	return 0
}

type BudgetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Scope         BudgetScope            `protobuf:"varint,2,opt,name=scope,proto3,enum=gateway.v1.BudgetScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetRef) Reset() {
	*x = BudgetRef{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetRef) ProtoMessage() {}

func (x *BudgetRef) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetRef.ProtoReflect.Descriptor instead.
func (*BudgetRef) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *BudgetRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetRef) GetScope() BudgetScope {
	if x != nil {
		return x.Scope
	}
	return BudgetScope_BUDGET_SCOPE_UNSPECIFIED
}

type Principal struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	KeyId  string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Tenant string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Org    string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Team   string                 `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	User   string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	App    string                 `protobuf:"bytes,6,opt,name=app,proto3" json:"app,omitempty"`
	Roles  []string               `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	// allow_all is explicit rather than implied by an empty list, so that an
	// empty allowlist means "nothing" and a builder that forgets to populate it
	// fails closed.
	ModelsAllowAll   bool         `protobuf:"varint,8,opt,name=models_allow_all,json=modelsAllowAll,proto3" json:"models_allow_all,omitempty"`
	Models           []string     `protobuf:"bytes,9,rep,name=models,proto3" json:"models,omitempty"`
	Budgets          []*BudgetRef `protobuf:"bytes,10,rep,name=budgets,proto3" json:"budgets,omitempty"`
	DefaultDataClass string       `protobuf:"bytes,11,opt,name=default_data_class,json=defaultDataClass,proto3" json:"default_data_class,omitempty"`
	MinTrustTier     TrustTier    `protobuf:"varint,12,opt,name=min_trust_tier,json=minTrustTier,proto3,enum=gateway.v1.TrustTier" json:"min_trust_tier,omitempty"`
	MaxConcurrent    uint32       `protobuf:"varint,13,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	// The outgoing generation of a rotated key stays valid until not_after, with
	// a warning header, so rotation is a non-event for callers.
	Deprecated     bool  `protobuf:"varint,14,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	NotAfterUnixMs int64 `protobuf:"varint,15,opt,name=not_after_unix_ms,json=notAfterUnixMs,proto3" json:"not_after_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *Principal) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Principal) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Principal) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Principal) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *Principal) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Principal) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Principal) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Principal) GetModelsAllowAll() bool {
	if x != nil {
		return x.ModelsAllowAll
	}
	return false
}

func (x *Principal) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Principal) GetBudgets() []*BudgetRef {
	if x != nil {
		return x.Budgets
	}
	return nil
}

func (x *Principal) GetDefaultDataClass() string {
	if x != nil {
		return x.DefaultDataClass
	}
	return ""
}

func (x *Principal) GetMinTrustTier() TrustTier {
	if x != nil {
		return x.MinTrustTier
	}
	return TrustTier_TRUST_TIER_UNSPECIFIED
}

func (x *Principal) GetMaxConcurrent() uint32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *Principal) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Principal) GetNotAfterUnixMs() int64 {
	if x != nil {
		return x.NotAfterUnixMs
	}
	return 0
}

// KeyEntry maps a key's lookup value to the principal it resolves to. The
// lookup is HMAC-SHA256 of the key secret under a pepper the worker holds and
// the snapshot never carries, so a stolen snapshot yields no usable key.
type KeyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lookup        []byte                 `protobuf:"bytes,1,opt,name=lookup,proto3" json:"lookup,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEntry) Reset() {
	*x = KeyEntry{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEntry) ProtoMessage() {}

func (x *KeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEntry.ProtoReflect.Descriptor instead.
func (*KeyEntry) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *KeyEntry) GetLookup() []byte {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *KeyEntry) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// GlobalLayer is the tenant-independent half of a snapshot: large, and changes
// rarely.
type GlobalLayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *LayerVersion          `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuiltAtUnixMs int64                  `protobuf:"varint,2,opt,name=built_at_unix_ms,json=builtAtUnixMs,proto3" json:"built_at_unix_ms,omitempty"`
	Deployments   []*Deployment          `protobuf:"bytes,3,rep,name=deployments,proto3" json:"deployments,omitempty"`
	Aliases       []*ModelAlias          `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// Routes an API key's prefix segment to a tenant, so principal lookup is one
	// probe into one tenant's map rather than a scan across every tenant.
	TenantPrefixes  map[string]string `protobuf:"bytes,5,rep,name=tenant_prefixes,json=tenantPrefixes,proto3" json:"tenant_prefixes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DefaultPlugins  []*PluginBinding  `protobuf:"bytes,6,rep,name=default_plugins,json=defaultPlugins,proto3" json:"default_plugins,omitempty"`
	PolicyBundleRef string            `protobuf:"bytes,7,opt,name=policy_bundle_ref,json=policyBundleRef,proto3" json:"policy_bundle_ref,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GlobalLayer) Reset() {
	*x = GlobalLayer{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLayer) ProtoMessage() {}

func (x *GlobalLayer) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLayer.ProtoReflect.Descriptor instead.
func (*GlobalLayer) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalLayer) GetVersion() *LayerVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GlobalLayer) GetBuiltAtUnixMs() int64 {
	if x != nil {
		return x.BuiltAtUnixMs
	}
	return 0
}

func (x *GlobalLayer) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *GlobalLayer) GetAliases() []*ModelAlias {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *GlobalLayer) GetTenantPrefixes() map[string]string {
	if x != nil {
		return x.TenantPrefixes
	}
	return nil
}

func (x *GlobalLayer) GetDefaultPlugins() []*PluginBinding {
	if x != nil {
		return x.DefaultPlugins
	}
	return nil
}

func (x *GlobalLayer) GetPolicyBundleRef() string {
	if x != nil {
		return x.PolicyBundleRef
	}
	return ""
}

// TenantLayer is one tenant's slice: small, and changes constantly. It is
// versioned and shipped independently of the global layer, so a budget edit
// does not reship the catalog to every worker.
type TenantLayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Version       *LayerVersion          `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuiltAtUnixMs int64                  `protobuf:"varint,3,opt,name=built_at_unix_ms,json=builtAtUnixMs,proto3" json:"built_at_unix_ms,omitempty"`
	// Plan tier. Safe as a metrics label, unlike the tenant id, which is
	// unbounded cardinality and will take Prometheus down.
	Tier           string           `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	Principals     []*Principal     `protobuf:"bytes,5,rep,name=principals,proto3" json:"principals,omitempty"`
	Keys           []*KeyEntry      `protobuf:"bytes,6,rep,name=keys,proto3" json:"keys,omitempty"`
	AliasOverrides []*ModelAlias    `protobuf:"bytes,7,rep,name=alias_overrides,json=aliasOverrides,proto3" json:"alias_overrides,omitempty"`
	Budgets        []*BudgetState   `protobuf:"bytes,8,rep,name=budgets,proto3" json:"budgets,omitempty"`
	Plugins        []*PluginBinding `protobuf:"bytes,9,rep,name=plugins,proto3" json:"plugins,omitempty"`
	MinTrustTier   TrustTier        `protobuf:"varint,10,opt,name=min_trust_tier,json=minTrustTier,proto3,enum=gateway.v1.TrustTier" json:"min_trust_tier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantLayer) Reset() {
	*x = TenantLayer{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantLayer) ProtoMessage() {}

func (x *TenantLayer) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantLayer.ProtoReflect.Descriptor instead.
func (*TenantLayer) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{11}
}

func (x *TenantLayer) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantLayer) GetVersion() *LayerVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *TenantLayer) GetBuiltAtUnixMs() int64 {
	if x != nil {
		return x.BuiltAtUnixMs
	}
	return 0
}

func (x *TenantLayer) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *TenantLayer) GetPrincipals() []*Principal {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (x *TenantLayer) GetKeys() []*KeyEntry {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TenantLayer) GetAliasOverrides() []*ModelAlias {
	if x != nil {
		return x.AliasOverrides
	}
	return nil
}

func (x *TenantLayer) GetBudgets() []*BudgetState {
	if x != nil {
		return x.Budgets
	}
	return nil
}

func (x *TenantLayer) GetPlugins() []*PluginBinding {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *TenantLayer) GetMinTrustTier() TrustTier {
	if x != nil {
		return x.MinTrustTier
	}
	return TrustTier_TRUST_TIER_UNSPECIFIED
}

// Snapshot is a global layer plus the tenant layers composed onto it. Layers
// are also transferable on their own; this message is the full-fetch form used
// on worker startup and after a watch stream gap.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Global        *GlobalLayer           `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	Tenants       []*TenantLayer         `protobuf:"bytes,2,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_gateway_v1_snapshot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_snapshot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_gateway_v1_snapshot_proto_rawDescGZIP(), []int{12}
}

func (x *Snapshot) GetGlobal() *GlobalLayer {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *Snapshot) GetTenants() []*TenantLayer {
	if x != nil {
		return x.Tenants
	}
	return nil
}

var File_gateway_v1_snapshot_proto protoreflect.FileDescriptor

const file_gateway_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/v1/snapshot.proto\x12\n" +
	"gateway.v1\">\n" +
	"\fLayerVersion\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"J\n" +
	"\n" +
	"RoutingKey\x12\x1d\n" +
	"\n" +
	"base_model\x18\x01 \x01(\tR\tbaseModel\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x02 \x01(\tR\tadapterId\"p\n" +
	"\x04Cost\x122\n" +
	"\x16input_per_1k_micro_usd\x18\x01 \x01(\x03R\x12inputPer1kMicroUsd\x124\n" +
	"\x17output_per_1k_micro_usd\x18\x02 \x01(\x03R\x13outputPer1kMicroUsd\"\xd5\x02\n" +
	"\n" +
	"Deployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x03key\x18\x02 \x01(\v2\x16.gateway.v1.RoutingKeyR\x03key\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x124\n" +
	"\n" +
	"trust_tier\x18\x06 \x01(\x0e2\x15.gateway.v1.TrustTierR\ttrustTier\x12%\n" +
	"\x0ecredential_ref\x18\a \x01(\tR\rcredentialRef\x12\x16\n" +
	"\x06weight\x18\b \x01(\rR\x06weight\x12$\n" +
	"\x04cost\x18\t \x01(\v2\x10.gateway.v1.CostR\x04cost\x12\"\n" +
	"\fcapabilities\x18\n" +
	" \x03(\tR\fcapabilities\"R\n" +
	"\n" +
	"ModelAlias\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\atargets\x18\x02 \x03(\v2\x16.gateway.v1.RoutingKeyR\atargets\"\x8c\x01\n" +
	"\rPluginBinding\x12$\n" +
	"\x04port\x18\x01 \x01(\x0e2\x10.gateway.v1.PortR\x04port\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"config_ref\x18\x04 \x01(\tR\tconfigRef\"\xe4\x01\n" +
	"\vBudgetState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x17.gateway.v1.BudgetScopeR\x05scope\x12&\n" +
	"\x0flimit_micro_usd\x18\x03 \x01(\x03R\rlimitMicroUsd\x12&\n" +
	"\x0fspent_micro_usd\x18\x04 \x01(\x03R\rspentMicroUsd\x12\x12\n" +
	"\x04hard\x18\x05 \x01(\bR\x04hard\x122\n" +
	"\x15headroom_basis_points\x18\x06 \x01(\rR\x13headroomBasisPoints\"J\n" +
	"\tBudgetRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x17.gateway.v1.BudgetScopeR\x05scope\"\xec\x03\n" +
	"\tPrincipal\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x12\n" +
	"\x04team\x18\x04 \x01(\tR\x04team\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x10\n" +
	"\x03app\x18\x06 \x01(\tR\x03app\x12\x14\n" +
	"\x05roles\x18\a \x03(\tR\x05roles\x12(\n" +
	"\x10models_allow_all\x18\b \x01(\bR\x0emodelsAllowAll\x12\x16\n" +
	"\x06models\x18\t \x03(\tR\x06models\x12/\n" +
	"\abudgets\x18\n" +
	" \x03(\v2\x15.gateway.v1.BudgetRefR\abudgets\x12,\n" +
	"\x12default_data_class\x18\v \x01(\tR\x10defaultDataClass\x12;\n" +
	"\x0emin_trust_tier\x18\f \x01(\x0e2\x15.gateway.v1.TrustTierR\fminTrustTier\x12%\n" +
	"\x0emax_concurrent\x18\r \x01(\rR\rmaxConcurrent\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x0e \x01(\bR\n" +
	"deprecated\x12)\n" +
	"\x11not_after_unix_ms\x18\x0f \x01(\x03R\x0enotAfterUnixMs\"9\n" +
	"\bKeyEntry\x12\x16\n" +
	"\x06lookup\x18\x01 \x01(\fR\x06lookup\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"\xdf\x03\n" +
	"\vGlobalLayer\x122\n" +
	"\aversion\x18\x01 \x01(\v2\x18.gateway.v1.LayerVersionR\aversion\x12'\n" +
	"\x10built_at_unix_ms\x18\x02 \x01(\x03R\rbuiltAtUnixMs\x128\n" +
	"\vdeployments\x18\x03 \x03(\v2\x16.gateway.v1.DeploymentR\vdeployments\x120\n" +
	"\aaliases\x18\x04 \x03(\v2\x16.gateway.v1.ModelAliasR\aaliases\x12T\n" +
	"\x0ftenant_prefixes\x18\x05 \x03(\v2+.gateway.v1.GlobalLayer.TenantPrefixesEntryR\x0etenantPrefixes\x12B\n" +
	"\x0fdefault_plugins\x18\x06 \x03(\v2\x19.gateway.v1.PluginBindingR\x0edefaultPlugins\x12*\n" +
	"\x11policy_bundle_ref\x18\a \x01(\tR\x0fpolicyBundleRef\x1aA\n" +
	"\x13TenantPrefixesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x03\n" +
	"\vTenantLayer\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x122\n" +
	"\aversion\x18\x02 \x01(\v2\x18.gateway.v1.LayerVersionR\aversion\x12'\n" +
	"\x10built_at_unix_ms\x18\x03 \x01(\x03R\rbuiltAtUnixMs\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x125\n" +
	"\n" +
	"principals\x18\x05 \x03(\v2\x15.gateway.v1.PrincipalR\n" +
	"principals\x12(\n" +
	"\x04keys\x18\x06 \x03(\v2\x14.gateway.v1.KeyEntryR\x04keys\x12?\n" +
	"\x0falias_overrides\x18\a \x03(\v2\x16.gateway.v1.ModelAliasR\x0ealiasOverrides\x121\n" +
	"\abudgets\x18\b \x03(\v2\x17.gateway.v1.BudgetStateR\abudgets\x123\n" +
	"\aplugins\x18\t \x03(\v2\x19.gateway.v1.PluginBindingR\aplugins\x12;\n" +
	"\x0emin_trust_tier\x18\n" +
	" \x01(\x0e2\x15.gateway.v1.TrustTierR\fminTrustTier\"n\n" +
	"\bSnapshot\x12/\n" +
	"\x06global\x18\x01 \x01(\v2\x17.gateway.v1.GlobalLayerR\x06global\x121\n" +
	"\atenants\x18\x02 \x03(\v2\x17.gateway.v1.TenantLayerR\atenants*w\n" +
	"\tTrustTier\x12\x1a\n" +
	"\x16TRUST_TIER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRUST_TIER_EXTERNAL\x10\x01\x12\x1c\n" +
	"\x18TRUST_TIER_PRIVATE_CLOUD\x10\x02\x12\x17\n" +
	"\x13TRUST_TIER_INTERNAL\x10\x03*\xce\x01\n" +
	"\vBudgetScope\x12\x1c\n" +
	"\x18BUDGET_SCOPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BUDGET_SCOPE_KEY\x10\x01\x12\x14\n" +
	"\x10BUDGET_SCOPE_APP\x10\x02\x12\x15\n" +
	"\x11BUDGET_SCOPE_USER\x10\x03\x12\x15\n" +
	"\x11BUDGET_SCOPE_TEAM\x10\x04\x12\x14\n" +
	"\x10BUDGET_SCOPE_ORG\x10\x05\x12\x16\n" +
	"\x12BUDGET_SCOPE_MODEL\x10\x06\x12\x19\n" +
	"\x15BUDGET_SCOPE_TRAINING\x10\a*g\n" +
	"\x04Port\x12\x14\n" +
	"\x10PORT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPORT_PROVIDER\x10\x01\x12\x12\n" +
	"\x0ePORT_GUARDRAIL\x10\x02\x12\x0e\n" +
	"\n" +
	"PORT_STORE\x10\x03\x12\x12\n" +
	"\x0ePORT_TELEMETRY\x10\x04BIZGgithub.com/umerjavaidkh/model-gateway/dataplane/internal/wire/gatewayv1b\x06proto3"

var (
	file_gateway_v1_snapshot_proto_rawDescOnce sync.Once
	file_gateway_v1_snapshot_proto_rawDescData []byte
)

func file_gateway_v1_snapshot_proto_rawDescGZIP() []byte {
	file_gateway_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_gateway_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_snapshot_proto_rawDesc), len(file_gateway_v1_snapshot_proto_rawDesc)))
	})
	return file_gateway_v1_snapshot_proto_rawDescData
}

var file_gateway_v1_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gateway_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gateway_v1_snapshot_proto_goTypes = []any{
	(TrustTier)(0),        // 0: gateway.v1.TrustTier
	(BudgetScope)(0),      // 1: gateway.v1.BudgetScope
	(Port)(0),             // 2: gateway.v1.Port
	(*LayerVersion)(nil),  // 3: gateway.v1.LayerVersion
	(*RoutingKey)(nil),    // 4: gateway.v1.RoutingKey
	(*Cost)(nil),          // 5: gateway.v1.Cost
	(*Deployment)(nil),    // 6: gateway.v1.Deployment
	(*ModelAlias)(nil),    // 7: gateway.v1.ModelAlias
	(*PluginBinding)(nil), // 8: gateway.v1.PluginBinding
	(*BudgetState)(nil),   // 9: gateway.v1.BudgetState
	(*BudgetRef)(nil),     // 10: gateway.v1.BudgetRef
	(*Principal)(nil),     // 11: gateway.v1.Principal
	(*KeyEntry)(nil),      // 12: gateway.v1.KeyEntry
	(*GlobalLayer)(nil),   // 13: gateway.v1.GlobalLayer
	(*TenantLayer)(nil),   // 14: gateway.v1.TenantLayer
	(*Snapshot)(nil),      // 15: gateway.v1.Snapshot
	nil,                   // 16: gateway.v1.GlobalLayer.TenantPrefixesEntry
}
var file_gateway_v1_snapshot_proto_depIdxs = []int32{
	4,  // 0: gateway.v1.Deployment.key:type_name -> gateway.v1.RoutingKey
	0,  // 1: gateway.v1.Deployment.trust_tier:type_name -> gateway.v1.TrustTier
	5,  // 2: gateway.v1.Deployment.cost:type_name -> gateway.v1.Cost
	4,  // 3: gateway.v1.ModelAlias.targets:type_name -> gateway.v1.RoutingKey
	2,  // 4: gateway.v1.PluginBinding.port:type_name -> gateway.v1.Port
	1,  // 5: gateway.v1.BudgetState.scope:type_name -> gateway.v1.BudgetScope
	1,  // 6: gateway.v1.BudgetRef.scope:type_name -> gateway.v1.BudgetScope
	10, // 7: gateway.v1.Principal.budgets:type_name -> gateway.v1.BudgetRef
	0,  // 8: gateway.v1.Principal.min_trust_tier:type_name -> gateway.v1.TrustTier
	3,  // 9: gateway.v1.GlobalLayer.version:type_name -> gateway.v1.LayerVersion
	6,  // 10: gateway.v1.GlobalLayer.deployments:type_name -> gateway.v1.Deployment
	7,  // 11: gateway.v1.GlobalLayer.aliases:type_name -> gateway.v1.ModelAlias
	16, // 12: gateway.v1.GlobalLayer.tenant_prefixes:type_name -> gateway.v1.GlobalLayer.TenantPrefixesEntry
	8,  // 13: gateway.v1.GlobalLayer.default_plugins:type_name -> gateway.v1.PluginBinding
	3,  // 14: gateway.v1.TenantLayer.version:type_name -> gateway.v1.LayerVersion
	11, // 15: gateway.v1.TenantLayer.principals:type_name -> gateway.v1.Principal
	12, // 16: gateway.v1.TenantLayer.keys:type_name -> gateway.v1.KeyEntry
	7,  // 17: gateway.v1.TenantLayer.alias_overrides:type_name -> gateway.v1.ModelAlias
	9,  // 18: gateway.v1.TenantLayer.budgets:type_name -> gateway.v1.BudgetState
	8,  // 19: gateway.v1.TenantLayer.plugins:type_name -> gateway.v1.PluginBinding
	0,  // 20: gateway.v1.TenantLayer.min_trust_tier:type_name -> gateway.v1.TrustTier
	13, // 21: gateway.v1.Snapshot.global:type_name -> gateway.v1.GlobalLayer
	14, // 22: gateway.v1.Snapshot.tenants:type_name -> gateway.v1.TenantLayer
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_gateway_v1_snapshot_proto_init() }
func file_gateway_v1_snapshot_proto_init() {
	if File_gateway_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_snapshot_proto_rawDesc), len(file_gateway_v1_snapshot_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_gateway_v1_snapshot_proto_depIdxs,
		EnumInfos:         file_gateway_v1_snapshot_proto_enumTypes,
		MessageInfos:      file_gateway_v1_snapshot_proto_msgTypes,
	}.Build()
	File_gateway_v1_snapshot_proto = out.File
	file_gateway_v1_snapshot_proto_goTypes = nil
	file_gateway_v1_snapshot_proto_depIdxs = nil
}
