// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: gateway/v1/usage.proto

// The usage event: one record per request, produced by the data plane and
// consumed by the control plane's accounting.
//
// It is a separate schema from the snapshot because the two travel in opposite
// directions and change for unrelated reasons. A snapshot is configuration
// pushed out; this is measurement flowing back.
//
// The stream is the source of truth for cost, so the same append-only
// compatibility rules apply: never reuse or renumber a tag, and a reader must
// tolerate fields it does not understand — during a rollout, a consumer older
// than its producers is normal.

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenUsage is what a request consumed, by billing class.
//
// The classes are disjoint: input excludes cached_input and cache_write. That
// is a normalisation the provider adapters perform, because providers disagree
// about whether cached tokens are counted inside the input total or beside it,
// and no consumer should have to know which one produced a record.
type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         int64                  `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	CachedInput   int64                  `protobuf:"varint,2,opt,name=cached_input,json=cachedInput,proto3" json:"cached_input,omitempty"`
	CacheWrite    int64                  `protobuf:"varint,3,opt,name=cache_write,json=cacheWrite,proto3" json:"cache_write,omitempty"`
	Output        int64                  `protobuf:"varint,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_gateway_v1_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_usage_proto_rawDescGZIP(), []int{0}
}

func (x *TokenUsage) GetInput() int64 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *TokenUsage) GetCachedInput() int64 {
	if x != nil {
		return x.CachedInput
	}
	return 0
}

func (x *TokenUsage) GetCacheWrite() int64 {
	if x != nil {
		return x.CacheWrite
	}
	return 0
}

func (x *TokenUsage) GetOutput() int64 {
	if x != nil {
		return x.Output
	}
	return 0
}

// UsageEvent is one served request.
//
// Emitted on every exit path, including refusals: a request rejected at
// admission consumed a slot worth counting, and one that failed after routing
// may already have burned tokens a provider will bill for.
type UsageEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is the trace id when tracing is on, so one string finds the
	// trace, this record and the log line.
	RequestId       string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimestampUnixMs int64  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Tenant          string `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	KeyId           string `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// tier is the tenant's plan tier. Safe as a metrics label, unlike tenant.
	Tier       string      `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	Deployment string      `protobuf:"bytes,6,opt,name=deployment,proto3" json:"deployment,omitempty"`
	BaseModel  string      `protobuf:"bytes,7,opt,name=base_model,json=baseModel,proto3" json:"base_model,omitempty"`
	AdapterId  string      `protobuf:"bytes,8,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	Provider   string      `protobuf:"bytes,9,opt,name=provider,proto3" json:"provider,omitempty"`
	Stream     bool        `protobuf:"varint,10,opt,name=stream,proto3" json:"stream,omitempty"`
	Usage      *TokenUsage `protobuf:"bytes,11,opt,name=usage,proto3" json:"usage,omitempty"`
	// cost is what the provider charges us; price is what the tenant is charged.
	// Equal until a rate card exists, and separate because budgets are enforced
	// against price and a negotiated rate makes them diverge.
	CostMicroUsd      int64 `protobuf:"varint,12,opt,name=cost_micro_usd,json=costMicroUsd,proto3" json:"cost_micro_usd,omitempty"`
	PriceMicroUsd     int64 `protobuf:"varint,13,opt,name=price_micro_usd,json=priceMicroUsd,proto3" json:"price_micro_usd,omitempty"`
	LatencyMs         int64 `protobuf:"varint,14,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TimeToFirstByteMs int64 `protobuf:"varint,15,opt,name=time_to_first_byte_ms,json=timeToFirstByteMs,proto3" json:"time_to_first_byte_ms,omitempty"`
	// outcome is empty on success, and otherwise the gateway's error code.
	Outcome string `protobuf:"bytes,16,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// snapshot_version records which configuration served the request. Without
	// it, "why did this route there" is unanswerable after a rollout.
	SnapshotVersion uint64 `protobuf:"varint,17,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	// budget_ids are the budgets this request must be charged against, captured
	// when it was served rather than looked up later. A budget detached from a
	// key afterwards would otherwise lose the spend that was incurred while it
	// was attached, and the arithmetic would quietly stop matching the invoice.
	BudgetIds []string `protobuf:"bytes,18,rep,name=budget_ids,json=budgetIds,proto3" json:"budget_ids,omitempty"`
	// shadow marks a mirrored request: one nobody was waiting for, whose answer
	// was discarded. It cost real money and belongs in the record, but it is not
	// traffic anybody was served — so accounting must be able to tell it apart
	// rather than charging a tenant for requests they did not make.
	Shadow bool `protobuf:"varint,19,opt,name=shadow,proto3" json:"shadow,omitempty"`
	// stages is how long each leg of the request took, in the order they ran.
	// Carried on the event because a trace answers "what happened to this
	// request" and this answers "which stage is slow across a thousand of
	// them" — and it survives without a trace backend.
	Stages        []*StageTiming `protobuf:"bytes,20,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageEvent) Reset() {
	*x = UsageEvent{}
	mi := &file_gateway_v1_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageEvent) ProtoMessage() {}

func (x *UsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageEvent.ProtoReflect.Descriptor instead.
func (*UsageEvent) Descriptor() ([]byte, []int) {
	return file_gateway_v1_usage_proto_rawDescGZIP(), []int{1}
}

func (x *UsageEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UsageEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *UsageEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *UsageEvent) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UsageEvent) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *UsageEvent) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *UsageEvent) GetBaseModel() string {
	if x != nil {
		return x.BaseModel
	}
	return ""
}

func (x *UsageEvent) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *UsageEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UsageEvent) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *UsageEvent) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *UsageEvent) GetCostMicroUsd() int64 {
	if x != nil {
		return x.CostMicroUsd
	}
	return 0
}

func (x *UsageEvent) GetPriceMicroUsd() int64 {
	if x != nil {
		return x.PriceMicroUsd
	}
	return 0
}

func (x *UsageEvent) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *UsageEvent) GetTimeToFirstByteMs() int64 {
	if x != nil {
		return x.TimeToFirstByteMs
	}
	return 0
}

func (x *UsageEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *UsageEvent) GetSnapshotVersion() uint64 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *UsageEvent) GetBudgetIds() []string {
	if x != nil {
		return x.BudgetIds
	}
	return nil
}

func (x *UsageEvent) GetShadow() bool {
	if x != nil {
		return x.Shadow
	}
	return false
}

func (x *UsageEvent) GetStages() []*StageTiming {
	if x != nil {
		return x.Stages
	}
	return nil
}

// StageTiming is one leg of the request path and what it cost.
type StageTiming struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the stage: authenticate, admit, guard, route, adapt.
	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DurationMs uint32 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// outcome is empty when the stage passed, and otherwise the code it refused
	// with. A stage that refused is where the request ended.
	Outcome       string `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageTiming) Reset() {
	*x = StageTiming{}
	mi := &file_gateway_v1_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageTiming) ProtoMessage() {}

func (x *StageTiming) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageTiming.ProtoReflect.Descriptor instead.
func (*StageTiming) Descriptor() ([]byte, []int) {
	return file_gateway_v1_usage_proto_rawDescGZIP(), []int{2}
}

func (x *StageTiming) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StageTiming) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StageTiming) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

// AuditEvent records a decision, where a UsageEvent records a measurement.
//
// That is the line between the two, and it is why they are separate messages on
// separate streams rather than one message with optional fields: a refusal, a
// redaction and a configuration change are things somebody decided, and they
// are kept append-only with a hash chain and their own retention clock. Token
// counts are things that happened, and they are aggregated and expired.
//
// The chain itself is not on this message. Two workers publishing concurrently
// would each need the previous record's hash to compute their own, and there is
// no previous record until one of them is written — so the chain is computed by
// the single consumer that appends, not by the producers.
type AuditEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id makes the record idempotent under at-least-once delivery. The
	// request id cannot: one request can produce a refusal and a redaction, and
	// a configuration change has no request at all.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// request_id is empty for actions that were not a request — a key rotation,
	// a policy publication.
	RequestId       string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimestampUnixMs int64  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Tenant          string `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// actor is who did it: a key id, a user subject, or a service-account name.
	Actor string `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	// action is what they did: "chat.completions", "key.issue", "policy.publish".
	Action string `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	// resource is what they did it to: a model, a deployment, a component.
	Resource string `protobuf:"bytes,7,opt,name=resource,proto3" json:"resource,omitempty"`
	// outcome is empty when the action was allowed, and otherwise the code it
	// was refused with.
	Outcome string `protobuf:"bytes,8,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// reason is the human-readable half of the outcome: which guardrail refused,
	// which rule matched. Never the payload that triggered it — the audit tap
	// sits after redaction precisely so this table does not become a copy of the
	// data it exists to protect.
	Reason string `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	// source_ip is the caller's address, for the "who and from where" an
	// investigation starts from.
	SourceIp string `protobuf:"bytes,10,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// snapshot_version is the configuration in force when the decision was made,
	// which is what makes "why was this allowed in March" answerable.
	SnapshotVersion uint64 `protobuf:"varint,11,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_gateway_v1_usage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_usage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_gateway_v1_usage_proto_rawDescGZIP(), []int{3}
}

func (x *AuditEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *AuditEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AuditEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AuditEvent) GetSnapshotVersion() uint64 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

var File_gateway_v1_usage_proto protoreflect.FileDescriptor

const file_gateway_v1_usage_proto_rawDesc = "" +
	"\n" +
	"\x16gateway/v1/usage.proto\x12\n" +
	"gateway.v1\"~\n" +
	"\n" +
	"TokenUsage\x12\x14\n" +
	"\x05input\x18\x01 \x01(\x03R\x05input\x12!\n" +
	"\fcached_input\x18\x02 \x01(\x03R\vcachedInput\x12\x1f\n" +
	"\vcache_write\x18\x03 \x01(\x03R\n" +
	"cacheWrite\x12\x16\n" +
	"\x06output\x18\x04 \x01(\x03R\x06output\"\xa6\x05\n" +
	"\n" +
	"UsageEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x12\x1e\n" +
	"\n" +
	"deployment\x18\x06 \x01(\tR\n" +
	"deployment\x12\x1d\n" +
	"\n" +
	"base_model\x18\a \x01(\tR\tbaseModel\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\b \x01(\tR\tadapterId\x12\x1a\n" +
	"\bprovider\x18\t \x01(\tR\bprovider\x12\x16\n" +
	"\x06stream\x18\n" +
	" \x01(\bR\x06stream\x12,\n" +
	"\x05usage\x18\v \x01(\v2\x16.gateway.v1.TokenUsageR\x05usage\x12$\n" +
	"\x0ecost_micro_usd\x18\f \x01(\x03R\fcostMicroUsd\x12&\n" +
	"\x0fprice_micro_usd\x18\r \x01(\x03R\rpriceMicroUsd\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x0e \x01(\x03R\tlatencyMs\x120\n" +
	"\x15time_to_first_byte_ms\x18\x0f \x01(\x03R\x11timeToFirstByteMs\x12\x18\n" +
	"\aoutcome\x18\x10 \x01(\tR\aoutcome\x12)\n" +
	"\x10snapshot_version\x18\x11 \x01(\x04R\x0fsnapshotVersion\x12\x1d\n" +
	"\n" +
	"budget_ids\x18\x12 \x03(\tR\tbudgetIds\x12\x16\n" +
	"\x06shadow\x18\x13 \x01(\bR\x06shadow\x12/\n" +
	"\x06stages\x18\x14 \x03(\v2\x17.gateway.v1.StageTimingR\x06stages\"\\\n" +
	"\vStageTiming\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\rR\n" +
	"durationMs\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\"\xce\x02\n" +
	"\n" +
	"AuditEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x14\n" +
	"\x05actor\x18\x05 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\a \x01(\tR\bresource\x12\x18\n" +
	"\aoutcome\x18\b \x01(\tR\aoutcome\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1b\n" +
	"\tsource_ip\x18\n" +
	" \x01(\tR\bsourceIp\x12)\n" +
	"\x10snapshot_version\x18\v \x01(\x04R\x0fsnapshotVersionBIZGgithub.com/umerjavaidkh/model-gateway/dataplane/internal/wire/gatewayv1b\x06proto3"

var (
	file_gateway_v1_usage_proto_rawDescOnce sync.Once
	file_gateway_v1_usage_proto_rawDescData []byte
)

func file_gateway_v1_usage_proto_rawDescGZIP() []byte {
	file_gateway_v1_usage_proto_rawDescOnce.Do(func() {
		file_gateway_v1_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_usage_proto_rawDesc), len(file_gateway_v1_usage_proto_rawDesc)))
	})
	return file_gateway_v1_usage_proto_rawDescData
}

var file_gateway_v1_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_v1_usage_proto_goTypes = []any{
	(*TokenUsage)(nil),  // 0: gateway.v1.TokenUsage
	(*UsageEvent)(nil),  // 1: gateway.v1.UsageEvent
	(*StageTiming)(nil), // 2: gateway.v1.StageTiming
	(*AuditEvent)(nil),  // 3: gateway.v1.AuditEvent
}
var file_gateway_v1_usage_proto_depIdxs = []int32{
	0, // 0: gateway.v1.UsageEvent.usage:type_name -> gateway.v1.TokenUsage
	2, // 1: gateway.v1.UsageEvent.stages:type_name -> gateway.v1.StageTiming
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateway_v1_usage_proto_init() }
func file_gateway_v1_usage_proto_init() {
	if File_gateway_v1_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_usage_proto_rawDesc), len(file_gateway_v1_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_usage_proto_goTypes,
		DependencyIndexes: file_gateway_v1_usage_proto_depIdxs,
		MessageInfos:      file_gateway_v1_usage_proto_msgTypes,
	}.Build()
	File_gateway_v1_usage_proto = out.File
	file_gateway_v1_usage_proto_goTypes = nil
	file_gateway_v1_usage_proto_depIdxs = nil
}
