# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/v1/usage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gateway/v1/usage.proto\x12\ngateway.v1\"V\n\nTokenUsage\x12\r\n\x05input\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61\x63hed_input\x18\x02 \x01(\x03\x12\x13\n\x0b\x63\x61\x63he_write\x18\x03 \x01(\x03\x12\x0e\n\x06output\x18\x04 \x01(\x03\"\xca\x03\n\nUsageEvent\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x02 \x01(\x03\x12\x0e\n\x06tenant\x18\x03 \x01(\t\x12\x0e\n\x06key_id\x18\x04 \x01(\t\x12\x0c\n\x04tier\x18\x05 \x01(\t\x12\x12\n\ndeployment\x18\x06 \x01(\t\x12\x12\n\nbase_model\x18\x07 \x01(\t\x12\x12\n\nadapter_id\x18\x08 \x01(\t\x12\x10\n\x08provider\x18\t \x01(\t\x12\x0e\n\x06stream\x18\n \x01(\x08\x12%\n\x05usage\x18\x0b \x01(\x0b\x32\x16.gateway.v1.TokenUsage\x12\x16\n\x0e\x63ost_micro_usd\x18\x0c \x01(\x03\x12\x17\n\x0fprice_micro_usd\x18\r \x01(\x03\x12\x12\n\nlatency_ms\x18\x0e \x01(\x03\x12\x1d\n\x15time_to_first_byte_ms\x18\x0f \x01(\x03\x12\x0f\n\x07outcome\x18\x10 \x01(\t\x12\x18\n\x10snapshot_version\x18\x11 \x01(\x04\x12\x12\n\nbudget_ids\x18\x12 \x03(\t\x12\x0e\n\x06shadow\x18\x13 \x01(\x08\x12\'\n\x06stages\x18\x14 \x03(\x0b\x32\x17.gateway.v1.StageTiming\"A\n\x0bStageTiming\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\r\x12\x0f\n\x07outcome\x18\x03 \x01(\t\"\xdc\x01\n\nAuditEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x03 \x01(\x03\x12\x0e\n\x06tenant\x18\x04 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\x12\x10\n\x08resource\x18\x07 \x01(\t\x12\x0f\n\x07outcome\x18\x08 \x01(\t\x12\x0e\n\x06reason\x18\t \x01(\t\x12\x11\n\tsource_ip\x18\n \x01(\t\x12\x18\n\x10snapshot_version\x18\x0b \x01(\x04\x42IZGgithub.com/umerjavaidkh/model-gateway/dataplane/internal/wire/gatewayv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway.v1.usage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGgithub.com/umerjavaidkh/model-gateway/dataplane/internal/wire/gatewayv1'
  _globals['_TOKENUSAGE']._serialized_start=38
  _globals['_TOKENUSAGE']._serialized_end=124
  _globals['_USAGEEVENT']._serialized_start=127
  _globals['_USAGEEVENT']._serialized_end=585
  _globals['_STAGETIMING']._serialized_start=587
  _globals['_STAGETIMING']._serialized_end=652
  _globals['_AUDITEVENT']._serialized_start=655
  _globals['_AUDITEVENT']._serialized_end=875
# @@protoc_insertion_point(module_scope)
