"""usage records

Revision ID: 00c0db03dc78
Revises: 5f9bcb89f153
Create Date: 2026-09-02 00:13:13.550026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c0db03dc78'
down_revision: Union[str, Sequence[str], None] = '5f9bcb89f153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_micro_usd', sa.Integer(), nullable=False),
    sa.Column('price_micro_usd', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_usage_records_key_id'), 'usage_records', ['key_id'], unique=False)
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_key_id'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
