"""finetune jobs

Revision ID: 3c4266882cdf
Revises: 4ff34a50585d
Create Date: 2026-09-02 16:55:28.734282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4266882cdf'
down_revision: Union[str, Sequence[str], None] = '4ff34a50585d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetune_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_model', sa.String(length=128), nullable=False),
    sa.Column('trainer', sa.String(length=64), nullable=False),
    sa.Column('trainer_version', sa.String(length=64), nullable=False),
    sa.Column('dataset_uri', sa.String(length=1024), nullable=False),
    sa.Column('dataset_checksum', sa.String(length=128), nullable=False),
    sa.Column('dataset_rows', sa.Integer(), nullable=False),
    sa.Column('dataset_schema_version', sa.String(length=64), nullable=False),
    sa.Column('hyperparameters', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('budget_ref', sa.String(length=64), server_default=sa.text("('')"), nullable=False),
    sa.Column('eval_suite', sa.String(length=64), server_default=sa.text("('')"), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), server_default=sa.text("('')"), nullable=False),
    sa.Column('artifact_ref', sa.String(length=512), server_default=sa.text("('')"), nullable=False),
    sa.Column('reason', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('cost_micro_usd', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_finetune_jobs_name'),
    sa.UniqueConstraint('idempotency_key', name='uq_finetune_jobs_idempotency_key')
    )
    op.create_index(op.f('ix_finetune_jobs_phase'), 'finetune_jobs', ['phase'], unique=False)
    op.create_index(op.f('ix_finetune_jobs_tenant_id'), 'finetune_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finetune_jobs_tenant_id'), table_name='finetune_jobs')
    op.drop_index(op.f('ix_finetune_jobs_phase'), table_name='finetune_jobs')
    op.drop_table('finetune_jobs')
    # ### end Alembic commands ###
