"""token class pricing

Revision ID: 5f9bcb89f153
Revises: ff2e066e7c43
Create Date: 2026-09-01 23:46:23.279961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9bcb89f153'
down_revision: Union[str, Sequence[str], None] = 'ff2e066e7c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('cached_input_cost_micro_usd', sa.Integer(), nullable=False))
    op.add_column('deployments', sa.Column('cache_write_cost_micro_usd', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'cache_write_cost_micro_usd')
    op.drop_column('deployments', 'cached_input_cost_micro_usd')
    # ### end Alembic commands ###
