"""component registry

Revision ID: 9585f3d34653
Revises: a041781914d5
Create Date: 2026-09-02 09:50:30.269179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9585f3d34653'
down_revision: Union[str, Sequence[str], None] = 'a041781914d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('config_schema', sa.Text(), nullable=False),
    sa.Column('latency_budget_ms', sa.Integer(), nullable=False),
    sa.Column('failure_mode', sa.String(length=16), nullable=False),
    sa.Column('execution', sa.String(length=16), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_components_name_version')
    )
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_index(op.f('ix_components_port'), 'components', ['port'], unique=False)
    op.create_table('component_admissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('suite', sa.String(length=32), nullable=False),
    sa.Column('suite_version', sa.String(length=64), nullable=False),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('runner', sa.String(length=255), nullable=False),
    sa.Column('evidence_ref', sa.String(length=512), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_admissions_component_id'), 'component_admissions', ['component_id'], unique=False)
    op.create_table('component_capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'name', name='uq_component_capabilities')
    )
    op.create_index(op.f('ix_component_capabilities_component_id'), 'component_capabilities', ['component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_component_capabilities_component_id'), table_name='component_capabilities')
    op.drop_table('component_capabilities')
    op.drop_index(op.f('ix_component_admissions_component_id'), table_name='component_admissions')
    op.drop_table('component_admissions')
    op.drop_index(op.f('ix_components_port'), table_name='components')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###
