"""policy rules

Revision ID: a041781914d5
Revises: 00c0db03dc78
Create Date: 2026-09-02 01:16:16.740364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a041781914d5'
down_revision: Union[str, Sequence[str], None] = '00c0db03dc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.Column('max_payload_bytes', sa.Integer(), nullable=False),
    sa.Column('data_class', sa.String(length=32), nullable=False),
    sa.Column('min_trust_tier', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rule_id', name='uq_policy_rules_id')
    )
    op.create_index(op.f('ix_policy_rules_tenant_id'), 'policy_rules', ['tenant_id'], unique=False)
    op.create_table('policy_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['policy_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_conditions_rule_id'), 'policy_conditions', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_conditions_rule_id'), table_name='policy_conditions')
    op.drop_table('policy_conditions')
    op.drop_index(op.f('ix_policy_rules_tenant_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    # ### end Alembic commands ###
