"""audit records

Revision ID: c09c26ae6bd4
Revises: 645415bffe99
Create Date: 2026-09-03 00:38:34.273596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09c26ae6bd4'
down_revision: Union[str, Sequence[str], None] = '645415bffe99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    # Assigned by the appender, not by the database. A serial here would let a
    # second writer take a position without reading the chain head, which is
    # exactly the fork the single-writer discipline exists to prevent.
    sa.Column('seq', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('snapshot_version', sa.BigInteger(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_records_action'), 'audit_records', ['action'], unique=False)
    op.create_index(op.f('ix_audit_records_occurred_at'), 'audit_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_records_tenant_id'), 'audit_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_records_tenant_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_occurred_at'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_action'), table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
