"""canary rollout

Revision ID: f349004e9362
Revises: 64c7133e5fe2
Create Date: 2026-09-02 18:37:34.149454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f349004e9362'
down_revision: Union[str, Sequence[str], None] = '64c7133e5fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finetune_jobs', sa.Column('rollout_step', sa.Integer(), server_default=sa.text('(-1)'), nullable=False))
    op.add_column('finetune_jobs', sa.Column('rollout_weight', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('finetune_jobs', sa.Column('canary_steps', sa.Text(), server_default=sa.text("'[1, 5, 25, 100]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finetune_jobs', 'canary_steps')
    op.drop_column('finetune_jobs', 'rollout_weight')
    op.drop_column('finetune_jobs', 'rollout_step')
    # ### end Alembic commands ###
