"""principal rate limits

Revision ID: ff2e066e7c43
Revises: c39e603fc180
Create Date: 2026-09-01 23:27:01.530724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2e066e7c43'
down_revision: Union[str, Sequence[str], None] = 'c39e603fc180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('requests_per_minute', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('tokens_per_minute', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'tokens_per_minute')
    op.drop_column('api_keys', 'requests_per_minute')
    # ### end Alembic commands ###
