package core

import (
	"crypto/hmac"
	"crypto/sha256"
	"strings"
	"time"
)

// The levels of the org -> team -> user -> application -> API key hierarchy.
// They are distinct named types rather than bare strings so that passing a
// TeamID where an OrgID belongs is a compile error, not a support ticket.
type (
	// TenantID is the billing and isolation boundary; it owns a snapshot layer.
	TenantID string
	// OrgID is the top of a tenant's identity graph.
	OrgID string
	// TeamID groups users and applications within an org.
	TeamID string
	// UserID is a human principal, usually authenticated by OIDC.
	UserID string
	// AppID is a service principal, usually authenticated by API key.
	AppID string
	// KeyID names one issued credential, of which a key may have two live
	// generations during rotation.
	KeyID string
)

// Role is a named permission set resolved by the control plane. The data plane
// never interprets role semantics; it hands the set to the policy engine.
type Role string

// KeyPrefix is the tenant-routing segment of an API key. Keys have the form
//
//	gw_<prefix>_<secret>
//
// The prefix is not a secret. It exists so that a presented key can be resolved
// to exactly one tenant layer before any cryptographic work happens, which is
// what keeps principal lookup a single hash probe rather than a scan across
// every tenant in the snapshot.
type KeyPrefix string

// KeyLookup is the value a snapshot indexes principals by: HMAC-SHA256 of the
// key's secret segment under a server-held pepper.
//
// The reference plan specifies Argon2id here. We deliberately do not use it.
// Argon2id exists to make offline cracking of *low-entropy* human-chosen
// passwords expensive, and it costs 10-100 ms by design. An API key secret is
// high-entropy random data generated by us, so there is nothing to crack and the
// cost buys nothing — while a 10-100 ms hash on the hot path would consume the
// entire latency budget many times over. A keyed HMAC gives what we actually
// need: constant-time comparison, and uselessness of a stolen database without
// the pepper.
type KeyLookup [sha256.Size]byte

// ComputeKeyLookup derives the snapshot lookup value for a key secret.
// The pepper is held by the worker and never appears in a snapshot.
func ComputeKeyLookup(pepper []byte, secret string) KeyLookup {
	mac := hmac.New(sha256.New, pepper)
	mac.Write([]byte(secret))
	var out KeyLookup
	copy(out[:], mac.Sum(nil))
	return out
}

// ParseAPIKey splits a presented key into its tenant prefix and secret segment.
// It validates shape only; whether the key exists is a snapshot lookup.
func ParseAPIKey(presented string) (KeyPrefix, string, error) {
	const scheme = "gw_"
	if !strings.HasPrefix(presented, scheme) {
		return "", "", New(CodeUnauthenticated, "api key has an unrecognised scheme")
	}
	prefix, secret, found := strings.Cut(presented[len(scheme):], "_")
	if !found || prefix == "" || secret == "" {
		return "", "", New(CodeUnauthenticated, "api key is malformed")
	}
	return KeyPrefix(prefix), secret, nil
}

// ModelAllowlist restricts which model aliases a principal may call.
//
// AllowAll is explicit rather than being implied by an empty Names list. An
// empty allowlist should mean "nothing", and a struct where the zero value is
// "deny everything" fails safe if a builder forgets to populate it.
type ModelAllowlist struct {
	AllowAll bool
	Names    []string
}

// Permits reports whether the principal may call the named alias or model.
func (a ModelAllowlist) Permits(name string) bool {
	if a.AllowAll {
		return true
	}
	for _, n := range a.Names {
		if n == name {
			return true
		}
	}
	return false
}

// RateLimit is what a principal may consume per window.
//
// Zero means unlimited for that dimension. That is the only safe default: a
// principal that predates a limit must not suddenly be capped at zero, which
// would turn adding a field into an outage.
//
// These are deliberately approximate. Requests per minute is enforced with a
// local lease in front of a shared window, so a boundary can over-admit
// slightly; tokens per minute is counted from reported usage and so lags by one
// request; concurrency is per worker. Budgets are the mechanism for anything
// that must be exactly right, and they are separate for exactly this reason.
type RateLimit struct {
	RequestsPerMinute uint32
	TokensPerMinute   uint32
	// MaxConcurrent is enforced per worker. The fleet-wide ceiling is this
	// multiplied by the worker count, which is stated rather than pretended
	// away — globally consistent concurrency limiting needs a round trip per
	// request and is not worth it.
	MaxConcurrent uint32
}

// Unlimited reports whether no dimension is capped.
func (r RateLimit) Unlimited() bool {
	return r.RequestsPerMinute == 0 && r.TokensPerMinute == 0 && r.MaxConcurrent == 0
}

// Principal is the precomputed identity record a key resolves to in one hash
// lookup. Every ancestor, the effective role set, the model allowlist and the
// whole budget chain are folded in by the control plane, so that admission never
// walks the identity graph at request time.
//
// OIDC/JWT callers and API-key callers both resolve to this same shape, which is
// what lets the policy engine see exactly one principal type.
//
// Principal is snapshot-resident: treat it as immutable (see package doc).
type Principal struct {
	KeyID  KeyID
	Tenant TenantID
	Org    OrgID
	Team   TeamID
	User   UserID
	App    AppID

	Roles        []Role
	Models       ModelAllowlist
	Budgets      []BudgetRef
	DefaultClass DataClass
	MinTrustTier TrustTier
	Limits       RateLimit

	// Deprecated marks the outgoing generation of a rotated key. It stays valid
	// until NotAfter, and the transport layer attaches a warning header. Two
	// generations overlapping is what makes rotation a non-event for callers.
	Deprecated bool
	NotAfter   time.Time
}

// Validate reports whether the principal may be used to serve a request now.
// It checks only time-based validity; permission checks belong to policy.
func (p *Principal) Validate(now time.Time) error {
	if !p.NotAfter.IsZero() && now.After(p.NotAfter) {
		return New(CodeUnauthenticated, "api key has expired")
	}
	return nil
}
